### ISSUE TITLE
synthetic lethal partners for mutations from large population dataset

### ISSUE THREAD

**Issue by Shicheng-Guo** [cbg-ethz/slidr#2]
Dear CBG team, 

I am curious do we have any package for synthetic lethal partners identification from WGS mutations from large population dataset (like biobank GEL, UBK etc)

Thanks. 

Shicheng

**Comment by anamus90** [comment]
Hi Shicheng,

Sorry, I'm not aware of any such packages. Since this is not an issue, I'll close this, but happy to continue this conversation via email. You can reach me at sumanasrivatsa@gmail.com.

Thanks,
Sumana
